
public class UncaughtExceptiion {

	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub

		
//		int[] j = new int[3];
//		
//		j[2]= 100;
//		System.out.println(j[1]);
//		//throw new Exception ("Eror occured");//Created our own exception to handle our errors is uncaught exception
//		//Q>>>>>Diff b/w throw & throws?
//	
		
		
		int [][] arr= new int [3][2];
//		try {
//		System.out.println(arr[0][0] = 100); 
//		System.out.println(arr[0][1] = 100); 
	System.out.println( arr[3][1] = 100);
//		 System.out.println(arr[2][1] = 100);
//		}
//		
//		catch(Exception e){
//			
//			System.out.println("Error was found");
//		}
//		
//		finally{
//			
//			System.out.println("Complete ");
//			
//			
//		}
}

}
